server:
    port: 8092
    error:
        include-message: always

spring:
    config:
        import: optional:configserver:

    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        platform: h2
        username: sa
        password: 

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            show_sql: true
            use_sql_comments: true
            format_sql: true

