server:
 port: 8092
 error:
  include-message: always

spring:
 h2:
  console:
   enabled: true
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  platform: h2
  username: sa
  password: 

 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
   show_sql: true
   use_sql_comments: true
   format_sql: true
   
eureka:
 instance:
  hostname: localhost
 client:
  serviceUrl: 
   defaultZone: http://localhost:8099/eureka/
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
management:
 endpoints:
  web:
   exposure:
    include: "*"
   
