server:
 port: 8093
 error:
  include-message: always

spring:
 h2:
  console:
   enabled: true
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  platform: h2
  username: sa
  password: 

 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
   show_sql: true
   use_sql_comments: true
   format_sql: true
feign:
 circuitbreaker:
  enabled: true
   
eureka:
 client:
  serviceUrl: 
   defaultZone: http://localhost:8099/eureka/
